### ISSUE TITLE
The cnc.py doesn't run 

### ISSUE THREAD

**Issue by merlin123h** [7h3w4lk3r/pyback#4]
Hi. 
According to attached picture, after configuring and other installation i want to run python3 or python2 cnc.py. Unfortunately this file can not be executed. It says that the module **Crypto** not installed, while i have installed it already.
Please help me to solve this problem.
Thanks 
![44](https://user-images.githubusercontent.com/67941449/106569739-caf2cf00-64e9-11eb-93ba-d420a6def2d7.PNG)

**Comment by 7h3w4lk3r** [comment]
Follow the installation and usage instructions step by step.
