### ISSUE TITLE
[Errno 10049]

### ISSUE THREAD

**Issue by r0m41** [7h3w4lk3r/pyback#6]
When run cnc.py i put ip and port. Then [Errno 10049]
![qqq](https://user-images.githubusercontent.com/64919602/108597293-010ccb80-7391-11eb-94f7-bc8bf32358ee.jpg)

**Comment by 7h3w4lk3r** [comment]
[Errno 10049] is not related to the script, your specifying an invalid IP address. check your input, im closing this.
